### ISSUE TITLE
galleria 403 on thumbs bucket

### ISSUE THREAD

**Issue by i001962** [evanchiu/serverless-galleria#2]
Evan, it looks like a similar 403 issue when using the galleria.

servePublic from:
...execute-api.us-east-1.amazonaws.com/Prod/ 

Inspecting the page shows this error:
 ...execute-api.us-east-1.amazonaws.com/api/thumb/AH512_512.jpg 403 ()
(fails on ...execute-api.us-east-1.amazonaws.com/Prod without the trailing / too)

Any suggestions? Both full and thumb buckets exist with the same file name(s) in them.

Kevin

**Comment by evanchiu** [comment]
Hey Kevin,

Thanks for the note!  Galleria only works with a [custom domain name](http://docs.aws.amazon.com/apigateway/latest/developerguide/how-to-custom-domains.html) configured.  The fix is doing what I [did for stu](https://github.com/evanchiu/stu/commit/a0ffc130bd95aa0a8c7ea466ef3677e31d7b7731); properly accounting the base path.  I intend to make a similar fix here, but if you don't want to wait for me, I welcome your pull request.

Thanks!
-Evan :D
