### ISSUE TITLE
A potentail risk in the uploader to escalate IAM permission for S3 bucktes.

### ISSUE THREAD

**Issue by zolaer9527** [evanchiu/serverless-galleria#78]
Hello! I found a potential risk in the uploader when I deployed it in the AWS Serverless Application Repository. 

### Detailed Analysis:
Before the uploader was deployed, it needed a parameter which is the name of a S3 Bucket. And the S3 Bucket must exist prior to deployment, but I found that I could construct the name of a bucket that didn't exist, even "*", which caused the permissions of the IAM role assigned to the application to be escalated. By the way, the runtime of this application must be nodejs18.x, but the runtime in the template is nodejs12.x.

### Impact:
In normal, the IAM role just can operate on the object of the specific S3 Bucket. But if the parameter is "*", the role can operate on the objects of all S3 Buckets.

### Mitigation Discussion:
1. The parameter which is the name of the S3 Bucket should be checked before the application is deployed. It must ensure that the Bucket exists and filters illegal parameters.

2. The version of runtime in the template should be updated to nodejs18.x.

### A Few Questions:
1. Is it a real issue in the uploader?
2. If it's a real issue, can any of my suggestions be used to solve this problem?

By the way, I have reported this issue to aws security team, and they said this problem cannot be resolved by AWS. But I didn't find your email, so I have to report this potential risk by creating a  GitHub issue. I'm sorry if there is any inconvenience.

Looking forward to your reply.
Regards,
Xunqi Liu

**Comment by zolaer9527** [comment]
Knock! Knock! Are there any updates?

**Comment by evanchiu** [comment]
Hello @zolaer9527!

I haven't tried it, but it does seem like you could deploy the uploader server less application to your AWS account with a bucket name of "*", which would give the role CRUD access to all S3 buckets in your AWS account.

This is mitigated in two ways:

1. The role is only accessible to the lambda, which would also need to be compromised to allow unrestricted use of the role.
2. The user providing the bucket name of * is someone who has access to deploy to the AWS account, so it's not like an attacker could use this serverless application to compromise your AWS account.

I'm not sure what capabilities are available in CloudFormation/Serverless Application Repository to confirm that the bucket exists prior to spinning up the stack, but I welcome your pull request on the topic.

Yes, it's been a while since I've worked on this project, and Lambda Runtime `nodejs12.x` went end of life [nearly a year ago on November 1, 2022](https://aws.amazon.com/blogs/developer/announcing-the-end-of-support-for-node-js-12-x-in-the-aws-sdk-for-javascript-v3/). I'll work on getting that updated.

**Comment by evanchiu** [comment]
Okay, Lambda runtime is updated for uploader in https://github.com/evanchiu/serverless-galleria/commit/98b12fb8dac1f34c4a3f047103e2885082034ceb

**Comment by zolaer9527** [comment]
Thanks for your reply @evanchiu!

Although the mitigations that you mentioned above could be useful, my point is that the permission after parameter “*” is entered as dest_bucket name is beyond what is necessary for this application. It seems like excessive permission. Just as you said, if an attacker compromised the lambda function, then he can take advantage of this excessive permission to compromise the AWS account. So I think maybe you should filter the parameters. For example, prohibiting input such as * as the name of the dest_bucket.

Anyway, I think it's a real potential risk. Would you like to give me a CVE number to commend me for discovering this problem?

Looking forward to your reply.
Best Regards.

**Comment by zolaer9527** [comment]
Knock! Knock! Are there any updates?

**Comment by evanchiu** [comment]
Hello @zolaer9527!

I’m not totally sure who you mean by commending you with a CVE number. My understanding of CVEs (and brief review of [CVEs and the NVD Process](https://nvd.nist.gov/general/cve-process)) indicates that CVEs are about software vulnerabilities, not config vulnerabilities. Any server software can be configured to be insecure. This should not be the default, but if an admin ignores the instructions and puts in unusual config that will cause the application to not work at deploy time, that doesn’t seem like a CVE to me.

Thanks!

**Comment by zolaer9527** [comment]
Thanks for your reply @evanchiu!

I understand what you're saying. But my key points are:
1. An attack can leverage the comprised lambda function to get CRUD access permission for all S3 buckets. Could it be a privilege escalation vulnerability? 
2. After that, the attack can leverage the CRUD access permission for all S3 buckets to steal sensitive information. Could it be an information leakage vulnerability?

Looking forward to your reply.
Best Regards.

**Comment by evanchiu** [comment]
Hello @zolaer9527,

If you have information about a weakness in the lambda that indicates a vulnerability, please share it, since both scenarios are predicated on a compromised lambda.

All you’ve said is that an administrator could ignore the instructions, then configure and deploy this application in a way that causes it not to work, which creates a role that has more permissions than necessary. Any server can be configured to have more access than necessary. I don’t see this misconfiguration as a privilege escalation or information leakage vulnerability.

Thanks!

**Comment by zolaer9527** [comment]
Hello @evanchiu ，
Thanks for your reply.
I carefully checked the source code and found that only the PutObject permission for S3 was used, while other permissions of   CRUD access to S3 buckets were not used. 
So are these permissions excessive? Can they be removed if they are unnecessary? For example. just use "S3:PutObject" to replace the S3CrudPolicy?
Looking forward to your reply!
Regards.

**Comment by evanchiu** [comment]
Hello @zolaer9527, that's a great idea!

Since writing this application 6 years ago, a new policy template [S3WritePolicy](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-policy-template-list.html#s3-write-policy) has been added, so that was an easy switch. This update is published in version 1.2.1 of [uploader](https://us-east-1.console.aws.amazon.com/lambda/home?region=us-east-1#/create/app?applicationId=arn:aws:serverlessrepo:us-east-1:233054207705:applications/uploader).

**Comment by zolaer9527** [comment]
Hello

**Comment by zolaer9527** [comment]
Hello @evanchiu, I'm glad to know it is fixed. By the way, could you give me a public thanks for awarding my efforts?

**Comment by evanchiu** [comment]
@zolaer9527, that's the stack name. The destBucket parameter still accepts `*`, and then the application fails to upload.

🙇 Thank you!

**Comment by zolaer9527** [comment]
@evanchiu, I'm sorry about that. Anyway, could you give me a public thanks for awarding my efforts?
Thank you!

**Comment by evanchiu** [comment]
@zolaer9527, what public thanks are you looking for? This issue is public.

**Comment by zolaer9527** [comment]
@evanchiu, maybe in the update announcement？

**Comment by evanchiu** [comment]
@zolaer9527 I'm not sure what update announcement you mean.

**Comment by zolaer9527** [comment]
@evanchiu, security advisories?

**Comment by evanchiu** [comment]
@zolaer9527, I don't have any plans to make any update announcements to any security advisories. Could you be more specific?

**Comment by zolaer9527** [comment]
Forget it, there is nothing.
Thank you.

**Comment by evanchiu** [comment]
Thanks again, @zolaer9527!
